export const GET_LIST = "GET_LIST";
export const GET_LIST_SUCCESS = "GET_LIST_SUCCESS";
export const GET_LIST_FAILURE = "GET_LIST_FAILURE";

export const GET_LIST_VIDEOS = "GET_LIST_VIDEOS";
export const GET_LIST_VIDEOS_SUCCESS = "GET_LIST_VIDEOS_SUCCESS";
export const GET_LIST_VIDEOS_FAILURE = "GET_LIST_VIDEOS_FAILURE";

export const GET_VIDEO = "GET_VIDEO";
export const GET_VIDEO_SUCCESS = "GET_VIDEO_SUCCESS";
export const GET_VIDEO_FAILURE = "GET_VIDEO_FAILURE";

export const GET_CHANNEL_DETAIL = "GET_CHANNEL_DETAIL";
export const GET_CHANNEL_DETAIL_SUCCESS = "GET_CHANNEL_DETAIL_SUCCESS";
export const GET_CHANNEL_DETAIL_FAILURE = "GET_CHANNEL_DETAIL_FAILURE";
